# Generated by Django 6.0.1 on 2026-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='my_price',
            field=models.IntegerField(default=0),
        ),
    ]
